name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t message-writer .

    - name: Run Docker container with volume
      run: docker run --name message-writer-container -v $(pwd)/output:/usr/src/app/output message-writer

    - name: Display output file
      run: cat ./output/output.txt
